In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_regression

X,y = make_regression(n_samples=10, n_features=5, n_informative=5, n_targets=1, random_state=42)

In [3]:
X

array([[-0.46947439,  1.57921282,  0.54256004,  0.76743473, -0.23413696],
       [-1.42474819, -0.2257763 , -0.54438272,  0.0675282 ,  1.46564877],
       [-0.60063869, -1.15099358, -0.29169375,  0.37569802,  0.11092259],
       [-0.90802408, -1.01283112, -1.4123037 ,  0.31424733, -0.56228753],
       [ 1.52302986, -0.1382643 , -0.23415337,  0.64768854,  0.49671415],
       [-0.3011037 ,  0.17136828, -1.47852199, -0.11564828,  0.73846658],
       [-1.91328024, -0.46572975, -1.72491783,  0.24196227, -0.46341769],
       [-1.05771093,  1.85227818,  0.82254491, -0.01349722, -0.60170661],
       [ 0.34361829, -0.46063877, -1.76304016,  1.05712223, -0.71984421],
       [-1.32818605,  0.2088636 ,  0.19686124, -1.95967012, -1.22084365]])

In [4]:
y

array([ 124.67279536, -179.5999463 , -169.77048128, -285.50639044,
        132.9604    , -120.60188828, -364.11253914,   99.14556097,
       -141.45435129, -130.93357704])

In [28]:
class MeraBatchGD:
  def __init__(self, iters, lr):
    self.w = None
    self.b = None
    self.iters = iters
    self.lr = lr
    self.loss_record = []

  def fit(self, X, y):

    # take samples, features
    # initialize w = 0, and b = 0

    samples,features = X.shape
    self.w = np.zeros(features)
    self.b = 0

    # training Loop
    for i in range(self.iters):

      # y_pred
      # residual
      # mse_loss (not needed though)
      # w_slope and b_slope
      # w and b -> update
      # loss_record -> append

      y_pred = np.dot(X, self.w) + self.b

      residual = y-y_pred

      mse_loss = np.mean((y-y_pred)**2)

      slope_w = -2/samples * np.dot(X.T , residual)
      slope_b = -2/samples * np.sum(residual)

      self.w = self.w - self.lr * slope_w
      self.b = self.b - self.lr * slope_b

      self.loss_record.append(mse_loss)
      if (i == self.iters - 1):
        print(f"MSE LOSS = {mse_loss}")
      elif (i == 0 or i%10 == 0):
        print(f"MSE LOSS = {mse_loss}")

      # In this case, the entire X and Y is used,
      # in Y_pred -> Whole X has gotten => much pressure in the memory to keep the Whole X in the memory for that instance

In [39]:
bgd = MeraBatchGD(iters = 100, lr = 0.6)

In [40]:
bgd.fit(X,y)

MSE LOSS = 36991.936384800705
MSE LOSS = 1448704202.7221344
MSE LOSS = 68436993209136.39
MSE LOSS = 3.232973328990165e+18
MSE LOSS = 1.527261215877963e+23
MSE LOSS = 7.214803786375833e+27
MSE LOSS = 3.408283608248353e+32
MSE LOSS = 1.610078042065453e+37
MSE LOSS = 7.606031655545329e+41
MSE LOSS = 3.593100212145232e+46
MSE LOSS = 5.785613410708388e+50


In [35]:
bgd.w

array([98.68869366, 80.21969808, 77.22447693,  7.45506437, 14.0924225 ])

In [46]:
class MeraStochasticGD:
  def __init__(self, epochs, lr):
    self.w = None
    self.b = None
    self.epochs = epochs
    self.lr = lr
    self.loss_record = []

  def fit(self, X, y):
    # just like batch GD
    samples, features = X.shape
    self.w = np.zeros(features)
    self.b = 0

    # thier are two loops
    # one for epochs -> How many times does it sees all the datapoints in dataset
    # one for samples -> loop for seeing all the datapoints in dataset

    for epoch in range(self.epochs):
      for i in range(samples):

        # just two steps to initialize
        # idx
        # xi and yi
        # and keep xi and yi, wherever thier is X, y

        idx = np.random.randint(0, samples)
        xi = X[idx]
        yi = y[idx]

        # after this all is same

        y_pred = np.dot(xi, self.w) + self.b
        residual = yi - y_pred

        mse_loss = (yi-y_pred)**2

        slope_w = -2 * xi * residual
        slope_b = -2 * residual

        self.w = self.w - self.lr * slope_w
        self.b = self.b - self.lr * slope_b

        self.loss_record.append(mse_loss)
        if (i == 0 or i%10 == 0):
          print(f"MSE LOSS = {mse_loss}")
        elif (i == samples - 1):
          print(f"MSE LOSS = {mse_loss}")



In [47]:
sgd = MeraStochasticGD(epochs = 100, lr = 0.1)

In [48]:
sgd.fit(X,y)

MSE LOSS = 28822.016314165925
MSE LOSS = 946.5481602055568
MSE LOSS = 613.5541292457747
MSE LOSS = 314.8400014199481
MSE LOSS = 409.80626733398395
MSE LOSS = 56.894717410471785
MSE LOSS = 863.7010533432202
MSE LOSS = 641.3728124835402
MSE LOSS = 186.42788245751896
MSE LOSS = 4.907840985351885
MSE LOSS = 6.535680559973115
MSE LOSS = 1.390846048269828
MSE LOSS = 0.003082092841224297
MSE LOSS = 2.459744087750353
MSE LOSS = 1.0314136901754254
MSE LOSS = 0.20791430875914213
MSE LOSS = 0.10106456011070454
MSE LOSS = 0.0015147873067176555
MSE LOSS = 8.231556321955605e-05
MSE LOSS = 0.09094941931216466
MSE LOSS = 0.004077802861647858
MSE LOSS = 0.011712828902826634
MSE LOSS = 0.7053608755282945
MSE LOSS = 0.3022695551296499
MSE LOSS = 0.32310322055039303
MSE LOSS = 0.004035413057682502
MSE LOSS = 0.007745973861355604
MSE LOSS = 1.162495115280947e-05
MSE LOSS = 0.005713266334836198
MSE LOSS = 0.028347346198286744
MSE LOSS = 0.008738075929958662
MSE LOSS = 1.365802513802538e-07
MSE LOSS = 0.0006