In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.datasets import make_regression
# import pprint

X,y = make_regression(n_samples=10, n_features=5, n_informative=5, n_targets=1, random_state=42)

print(X)

print(f"\n----\n {y}")


[[-0.46947439  1.57921282  0.54256004  0.76743473 -0.23413696]
 [-1.42474819 -0.2257763  -0.54438272  0.0675282   1.46564877]
 [-0.60063869 -1.15099358 -0.29169375  0.37569802  0.11092259]
 [-0.90802408 -1.01283112 -1.4123037   0.31424733 -0.56228753]
 [ 1.52302986 -0.1382643  -0.23415337  0.64768854  0.49671415]
 [-0.3011037   0.17136828 -1.47852199 -0.11564828  0.73846658]
 [-1.91328024 -0.46572975 -1.72491783  0.24196227 -0.46341769]
 [-1.05771093  1.85227818  0.82254491 -0.01349722 -0.60170661]
 [ 0.34361829 -0.46063877 -1.76304016  1.05712223 -0.71984421]
 [-1.32818605  0.2088636   0.19686124 -1.95967012 -1.22084365]]

----
 [ 124.67279536 -179.5999463  -169.77048128 -285.50639044  132.9604
 -120.60188828 -364.11253914   99.14556097 -141.45435129 -130.93357704]


In [ ]:
class MeraLR:
    def __init__(self, iterations, lr):
        self.w = None
        self.b = None
        self.iterations = iterations
        self.lr = lr
        self.loss_record = []

    def fit(self, X, y):
        samples, features = X.shape

        self.w = np.zeros(features)
        self.b = 0

        for i in range(self.iterations):

            # get y_pred ( = sample_dimension)
            # get residual ( = sample_dimension)
            # get mse_loss ( single value )
            # get slope of w and b
            # update w_new and b_new
            # append in loss_record

            y_pred = np.dot(X, self.w) + self.b

            residuals = y - y_pred

            mse = np.mean((y-y_pred)**2)

            n = len(y)

            slope_w = -2/n * np.dot(X.T, residuals)
            slope_b = -2/n * np.sum(residuals)

            self.w = self.w - self.lr*slope_w
            self.b = self.b - self.lr*slope_b

            print(f"for iteration {i} --- \nw = {self.w}\nb = {self.b}")

            # bUT HERE noticing part is that the entire X and y_actual is getting used and getting derivated to calc residual, mse, and  slopes

In [4]:
lr_mera = MeraLR(100, 0.1)



In [5]:
lr_mera.fit(X,y)

for iteration 0 --- 
w = [30.2893515  21.47986134 33.97131135  0.95449675  3.94042751]
b = -20.70400834869741
for iteration 1 --- 
w = [48.04282991 35.8727447  52.95583546  2.90611096  6.29164337]
b = -29.65189405634967
for iteration 2 --- 
w = [58.85470798 45.89597003 63.62174819  5.15041677  7.76267857]
b = -32.50636145717729
for iteration 3 --- 
w = [65.78131718 53.13464366 69.65321179  7.33413503  8.73682863]
b = -32.311769586705736
for iteration 4 --- 
w = [70.49518881 58.532827   73.09061895  9.29435499  9.42199932]
b = -30.688693699684237
for iteration 5 --- 
w = [73.9147862  62.66750858 75.0674686  10.96976637  9.93187955]
b = -28.486211472912267
for iteration 6 --- 
w = [76.54779164 65.90234223 76.21591484 12.35175462 10.32962226]
b = -26.13757999142034
for iteration 7 --- 
w = [78.67804976 68.47460769 76.89025477 13.45759111 10.65126113]
b = -23.8537772229915
for iteration 8 --- 
w = [80.46725838 70.54492077 77.2902913  14.31588006 10.91821268]
b = -21.728494270696388
for ite

In [6]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [7]:
lr.fit(X,y)

LinearRegression()

In [8]:
lr.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [9]:
print(lr.coef_)
print(lr.intercept_)

[98.68869366 80.21969808 77.22447693  7.45506437 14.0924225 ]
7.105427357601002e-14


In [ ]:
w = [ 98.6026833 , 80.17776331 , 77.28207754 , 7.5859391 , 14.05281039]
b = -0.05831459819265631